/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvac_system;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author Rahul
 */
public class HvacNavigation extends javax.swing.JFrame {

    /**
     * Creates new form HvacNavigation
     */
    public HvacNavigation() {
        initComponents();
        editfalse();
        this.pack();
       this.setTitle("HVAC System");
       aqiMeaning.setLineWrap(true);
       aqiMeaning.setWrapStyleWord(true);
          this.getContentPane().setBackground((Color.gray));
         this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    void editfalse()
    {
//        this.setVisible(true);
                        currentacTemperature.setEditable(false);
                        currentacStatus.setEditable(false);
                        currentheaterTemperature.setEditable(false);
                        currentheaterStatus.setEditable(false);
                        currentfanSpeed.setEditable(false);
                        currentfanStatus.setEditable(false);
                        aqi.setEditable(false);
                        currentexhaustStatus.setEditable(false);
                        currentexhaustSpeed.setEditable(false);
                        currenthumiditycontrollerStatus.setEditable(false);
                        currenthumidity.setEditable(false);
                        aqi.setEditable(false);
                        aqiMeaning.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentacTemperature = new javax.swing.JTextField();
        currentacStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentheaterStatus = new javax.swing.JTextField();
        currentheaterTemperature = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        currentexhaustStatus = new javax.swing.JTextField();
        currentexhaustSpeed = new javax.swing.JTextField();
        currentfanStatus = new javax.swing.JTextField();
        currentfanSpeed = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        currenthumiditycontrollerStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        currenthumidity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aqi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aqiMeaning = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(870, 593));
        setMinimumSize(new java.awt.Dimension(870, 593));
        setPreferredSize(new java.awt.Dimension(870, 593));
        setSize(new java.awt.Dimension(870, 593));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentacTemperature.setBackground(new java.awt.Color(204, 204, 204));
        currentacTemperature.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentacTemperature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentacTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentacTemperatureActionPerformed(evt);
            }
        });
        getContentPane().add(currentacTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 100, 148, 31));

        currentacStatus.setBackground(new java.awt.Color(204, 204, 204));
        currentacStatus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentacStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentacStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentacStatusActionPerformed(evt);
            }
        });
        getContentPane().add(currentacStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 100, 77, 31));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setText("  Air Conditioner");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 154, 31));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setText("  Status");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 33, 77, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Temperature");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 29, 148, 32));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("  Heater");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 158, 154, 30));

        currentheaterStatus.setBackground(new java.awt.Color(204, 204, 204));
        currentheaterStatus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentheaterStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(currentheaterStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 158, 77, -1));

        currentheaterTemperature.setBackground(new java.awt.Color(204, 204, 204));
        currentheaterTemperature.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentheaterTemperature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentheaterTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentheaterTemperatureActionPerformed(evt);
            }
        });
        getContentPane().add(currentheaterTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 158, 148, 31));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setText("  Status");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 216, 77, 27));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setText("    Speed");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 216, 97, 27));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setText("  Fan");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 250, 93, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setText("  Exhaust");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 315, 154, -1));

        currentexhaustStatus.setBackground(new java.awt.Color(204, 204, 204));
        currentexhaustStatus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentexhaustStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(currentexhaustStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 313, 77, 31));

        currentexhaustSpeed.setBackground(new java.awt.Color(204, 204, 204));
        currentexhaustSpeed.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentexhaustSpeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentexhaustSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentexhaustSpeedActionPerformed(evt);
            }
        });
        getContentPane().add(currentexhaustSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 313, 148, 31));

        currentfanStatus.setBackground(new java.awt.Color(204, 204, 204));
        currentfanStatus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentfanStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(currentfanStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 250, 77, 32));

        currentfanSpeed.setBackground(new java.awt.Color(204, 204, 204));
        currentfanSpeed.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currentfanSpeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(currentfanSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 250, 148, 32));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setText("  Humidity Controller");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 406, 192, 25));

        currenthumiditycontrollerStatus.setBackground(new java.awt.Color(204, 204, 204));
        currenthumiditycontrollerStatus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currenthumiditycontrollerStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currenthumiditycontrollerStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currenthumiditycontrollerStatusActionPerformed(evt);
            }
        });
        getContentPane().add(currenthumiditycontrollerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 405, 77, 25));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel10.setText("  Status");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 362, 77, 25));

        currenthumidity.setBackground(new java.awt.Color(204, 204, 204));
        currenthumidity.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        currenthumidity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currenthumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currenthumidityActionPerformed(evt);
            }
        });
        getContentPane().add(currenthumidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 405, 148, 26));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel11.setText("Current Humidity");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 362, -1, 25));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel12.setText("Air Quality in ppm");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 478, 192, -1));

        aqi.setBackground(new java.awt.Color(204, 204, 204));
        aqi.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        aqi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(aqi, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 476, 77, -1));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel13.setText("Meaning");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        aqiMeaning.setBackground(new java.awt.Color(204, 204, 204));
        aqiMeaning.setColumns(20);
        aqiMeaning.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        aqiMeaning.setRows(5);
        aqiMeaning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(aqiMeaning);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 332, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 586));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentacTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentacTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentacTemperatureActionPerformed

    private void currentacStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentacStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentacStatusActionPerformed

    private void currentheaterTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentheaterTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentheaterTemperatureActionPerformed

    private void currentexhaustSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentexhaustSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentexhaustSpeedActionPerformed

    private void currenthumiditycontrollerStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currenthumiditycontrollerStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currenthumiditycontrollerStatusActionPerformed

    private void currenthumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currenthumidityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currenthumidityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HvacNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HvacNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HvacNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HvacNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HvacNavigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField aqi;
    public javax.swing.JTextArea aqiMeaning;
    public javax.swing.JTextField currentacStatus;
    public javax.swing.JTextField currentacTemperature;
    public javax.swing.JTextField currentexhaustSpeed;
    public javax.swing.JTextField currentexhaustStatus;
    public javax.swing.JTextField currentfanSpeed;
    public javax.swing.JTextField currentfanStatus;
    public javax.swing.JTextField currentheaterStatus;
    public javax.swing.JTextField currentheaterTemperature;
    public javax.swing.JTextField currenthumidity;
    public javax.swing.JTextField currenthumiditycontrollerStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
