/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvac_system;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JSlider;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Rahul
 */
public final class HvacController extends javax.swing.JFrame {

    /**
     * Creates new form HvacController
     */
    public HvacController() {
        initComponents();
        showDate();
        showTime();
        this.setTitle("HVAC Systerm");
         RadioButton();
         clear();
         fan();
         this.pack();
         
        this.getContentPane().setBackground((Color.gray));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
     ButtonGroup bg=new ButtonGroup();
       ButtonGroup bg2=new ButtonGroup();
    void fan()
    {
         fanSpeed.setPaintTrack(true); 
        fanSpeed.setPaintTicks(true); 
        fanSpeed.setPaintLabels(true); 
        fanSpeed.setFont(new Font("Serif", Font.ITALIC, 20));
       fanSpeed.setMajorTickSpacing(10);
        fanSpeed.setMinorTickSpacing(1);
        fanSpeed.setValue(0);
        fanSpeed.setEnabled(false);
    }
   
    void clear()
    {
        temperature.setText(null);
        humidity.setText(null);
        airQuality.setText(null);
        bg.clearSelection();
        bg2.clearSelection();
       // fanSpeed = rescale.filter(fanSpeed,null);
       jLabel7.setText(" ");
       jLabel8.setText(" ");
       jLabel9.setText(" ");
       fan();
        
    }
    void RadioButton()
    {
         
        bg.add(summerMode);
        bg.add(winterMode);
        bg.add(autoMode);
          
        bg2.add(fanOff);
        bg2.add(fanOn);
        
    }
     void showDate()
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEE, dd-MM-yyyy");
        dateLab.setText("Date:"+s.format(d));
        
    }
    void showTime()
    {
        new Timer(0, (ActionEvent e) -> {
            Date d=new Date();
            SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
            timeLab.setText("Time:"+s.format(d));
        }).start();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        temperature = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        dateLab = new javax.swing.JLabel();
        timeLab = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        humidity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        airQuality = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fanOff = new javax.swing.JRadioButton();
        fanOn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        fanSpeed = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        autoMode = new javax.swing.JRadioButton();
        summerMode = new javax.swing.JRadioButton();
        winterMode = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(878, 593, 593, 593));
        setMaximumSize(new java.awt.Dimension(878, 593));
        setMinimumSize(new java.awt.Dimension(878, 593));
        setPreferredSize(new java.awt.Dimension(878, 593));
        setSize(new java.awt.Dimension(878, 593));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setText("Enter Temperature in °C");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 62, 215, 37));

        temperature.setBackground(new java.awt.Color(204, 204, 204));
        temperature.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        temperature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        temperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temperatureMouseClicked(evt);
            }
        });
        temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureActionPerformed(evt);
            }
        });
        temperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                temperatureKeyPressed(evt);
            }
        });
        getContentPane().add(temperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 182, 37));

        Submit.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 120, -1));

        dateLab.setBackground(new java.awt.Color(0, 0, 255));
        dateLab.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        dateLab.setForeground(new java.awt.Color(255, 255, 255));
        dateLab.setText("Date:");
        dateLab.setOpaque(true);
        getContentPane().add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 205, 26));

        timeLab.setBackground(new java.awt.Color(0, 0, 255));
        timeLab.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        timeLab.setForeground(new java.awt.Color(255, 255, 255));
        timeLab.setText("Time:");
        timeLab.setOpaque(true);
        getContentPane().add(timeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 197, 26));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Enter Humidity");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 139, 215, 37));

        humidity.setBackground(new java.awt.Color(204, 204, 204));
        humidity.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        humidity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        humidity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                humidityMouseClicked(evt);
            }
        });
        humidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                humidityKeyPressed(evt);
            }
        });
        getContentPane().add(humidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 180, 37));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setText("Enter Air Quality");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 220, 215, 37));

        airQuality.setBackground(new java.awt.Color(204, 204, 204));
        airQuality.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        airQuality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        airQuality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airQualityMouseClicked(evt);
            }
        });
        airQuality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                airQualityKeyPressed(evt);
            }
        });
        getContentPane().add(airQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 180, 37));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("Fan Status");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 291, 215, 37));

        fanOff.setBackground(new java.awt.Color(204, 204, 204));
        fanOff.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        fanOff.setText("OFF");
        fanOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fanOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fanOffActionPerformed(evt);
            }
        });
        getContentPane().add(fanOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        fanOn.setBackground(new java.awt.Color(204, 204, 204));
        fanOn.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        fanOn.setText("ON");
        fanOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fanOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fanOnActionPerformed(evt);
            }
        });
        getContentPane().add(fanOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setText("Fan Speed");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 356, 215, 37));

        fanSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fanSpeedStateChanged(evt);
            }
        });
        getContentPane().add(fanSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 465, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setText("MODE");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 436, 215, 37));

        autoMode.setBackground(new java.awt.Color(204, 204, 204));
        autoMode.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        autoMode.setText("Auto");
        autoMode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(autoMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 436, -1, 37));

        summerMode.setBackground(new java.awt.Color(204, 204, 204));
        summerMode.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        summerMode.setText("Summer");
        summerMode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(summerMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, 37));

        winterMode.setBackground(new java.awt.Color(204, 204, 204));
        winterMode.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        winterMode.setText("Winter");
        winterMode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(winterMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, 37));

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 180, 24));

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 175, 180, 27));

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 264, 132, 22));

        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton1.setText("Random Input");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 100, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(875, 580));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void fanSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fanSpeedStateChanged
        // TODO add your handling code here:
        String speed;
        speed = Integer.toString(fanSpeed.getValue());
         jLabel5.setText("Fan Speed: "+ speed);
    }//GEN-LAST:event_fanSpeedStateChanged

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
          //  Submit.setBackground((Color.BLUE));        // TODO add your handling code here:
          this.setCursor(getCursor());
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
       // Submit.setBackground((Color.ORANGE));
         if(temperature.getText().trim().isEmpty())
    {
        jLabel7.setText("Temperature field empty");
    }
        if(humidity.getText().trim().isEmpty())
        {
            jLabel8.setText("Humidity field empty");
        }
        if(airQuality.getText().trim().isEmpty())
        {
            jLabel9.setText("Aqi field empty");
        }
        this.setCursor(getCursor());
    }//GEN-LAST:event_SubmitMouseClicked

    private void temperatureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temperatureKeyPressed

        // TODO add your handling code here:
        jLabel7.setForeground(Color.RED);
        if(temperature.getText().length()==0)
        {
            jLabel7.setText(" ");
        }
        else{
        try{
            double d=Double.parseDouble(temperature.getText());
            jLabel7.setText(" ");
        }catch(NumberFormatException e)
        {
            jLabel7.setText("Invalid Input");
        }
        }
    }//GEN-LAST:event_temperatureKeyPressed

    private void humidityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_humidityKeyPressed
        // TODO add your handling code here:
        jLabel8.setForeground(Color.RED);
        if(humidity.getText().length()==0)
        {
           jLabel8.setText(" ");
        }
        else{
         try{
            double d=Double.parseDouble(humidity.getText());
            jLabel8.setText(" ");
        }catch(NumberFormatException e)
        {
            jLabel8.setText("Invalid Input");
        }
                }
    }//GEN-LAST:event_humidityKeyPressed

    private void airQualityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_airQualityKeyPressed
        // TODO add your handling code here:
        jLabel9.setForeground(Color.RED);
        if(airQuality.getText().length()==0)
        {
            jLabel9.setText(" ");
        }
        else{
        try{
            double d=Double.parseDouble(airQuality.getText());
            jLabel9.setText(" ");
        }catch(NumberFormatException e)
        {
            jLabel9.setText("Invalid Input");
        }
        }
    }//GEN-LAST:event_airQualityKeyPressed

    private void fanOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fanOnActionPerformed
        // TODO add your handling code here:
        fanSpeed.setEnabled(true);
    }//GEN-LAST:event_fanOnActionPerformed

    private void fanOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fanOffActionPerformed
        // TODO add your handling code here:
        fanSpeed.setEnabled(false);
    }//GEN-LAST:event_fanOffActionPerformed

    private void temperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperatureMouseClicked
        // TODO add your handling code here:
       // temperature.selectAll();
        if (evt.getClickCount() == 1 && SwingUtilities.isLeftMouseButton(evt)) {
          temperature.selectAll();
        }
    }//GEN-LAST:event_temperatureMouseClicked

    private void humidityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humidityMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 1 && SwingUtilities.isLeftMouseButton(evt)) {
          humidity.selectAll();
        }
    }//GEN-LAST:event_humidityMouseClicked

    private void airQualityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airQualityMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 1 && SwingUtilities.isLeftMouseButton(evt)) {
          airQuality.selectAll();
        }
    }//GEN-LAST:event_airQualityMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.setCursor(getCursor());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        temperature.setText("");
        humidity.setText("");
        airQuality.setText("");
        bg.clearSelection();
        bg2.clearSelection();
        fanSpeed.setEnabled(false);
        fanSpeed.setValue(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HvacController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HvacController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HvacController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HvacController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HvacController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Submit;
    public javax.swing.JTextField airQuality;
    public javax.swing.JRadioButton autoMode;
    private javax.swing.JLabel dateLab;
    public javax.swing.JRadioButton fanOff;
    public javax.swing.JRadioButton fanOn;
    public javax.swing.JSlider fanSpeed;
    public javax.swing.JTextField humidity;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JRadioButton summerMode;
    public javax.swing.JTextField temperature;
    private javax.swing.JLabel timeLab;
    public javax.swing.JRadioButton winterMode;
    // End of variables declaration//GEN-END:variables
}
